# Generated by Django 5.2.3 on 2025-06-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_viewhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
