# Generated by Django 5.2.3 on 2025-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_department_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
